/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package counsil;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Jarek
 */
public class InteractionMenu extends javax.swing.JFrame {

    private boolean raisedHand = false; //! todo

    public InteractionMenu(String role) {
        initComponents();
        System.out.println("My role is:" + Main.getUniversePeer().getLocalNode().getMyEndpointUserRole().getMyRole());
        if(Main.getUniversePeer().getLocalNode().getMyEndpointUserRole().getMyRole().equals("interpreter")) {
            System.out.println("Removing button");
            getContentPane().remove(WantToTalkButton);
            invalidate();
            repaint();
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        WantToTalkButton = new javax.swing.JButton();
        DisconnectButton = new javax.swing.JButton();
        ResetLayoutJButton = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        setResizable(false);

        WantToTalkButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        WantToTalkButton.setText("Raise hand");
        WantToTalkButton.setMaximumSize(new java.awt.Dimension(109, 25));
        WantToTalkButton.setMinimumSize(new java.awt.Dimension(109, 25));
        WantToTalkButton.setPreferredSize(new java.awt.Dimension(117, 31));
        WantToTalkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WantToTalkButtonActionPerformed(evt);
            }
        });

        DisconnectButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DisconnectButton.setText("Quit");
        DisconnectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisconnectButtonActionPerformed(evt);
            }
        });

        ResetLayoutJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ResetLayoutJButton.setText("Reset layout");
        ResetLayoutJButton.setPreferredSize(new java.awt.Dimension(117, 31));
        ResetLayoutJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetLayoutJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DisconnectButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(WantToTalkButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ResetLayoutJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(WantToTalkButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ResetLayoutJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DisconnectButton, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void WantToTalkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WantToTalkButtonActionPerformed
        if (raisedHand) {
            WantToTalkButton.setText("Raise hand");
            //! todo
        } else {
            WantToTalkButton.setText("Lower hand");
              //! todo
        }
        raisedHand = !raisedHand;

    }//GEN-LAST:event_WantToTalkButtonActionPerformed

    private void DisconnectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisconnectButtonActionPerformed
        String message = "Do you really want to quit CoUnSil?";
        String title = "Quit CoUnSil?";
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            quitCoUnSil();
        }
    }//GEN-LAST:event_DisconnectButtonActionPerformed

    private void ResetLayoutJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetLayoutJButtonActionPerformed
        // TODO add your handling code here:
        //UserController.getInstance().refreshLayout();
    }//GEN-LAST:event_ResetLayoutJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InteractionMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InteractionMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InteractionMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InteractionMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InteractionMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DisconnectButton;
    private javax.swing.JButton ResetLayoutJButton;
    private javax.swing.JButton WantToTalkButton;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

    private void quitCoUnSil() {
            //! todo
        try {
            Thread.sleep(1000);
        } catch (InterruptedException ex) {
            Logger.getLogger(InteractionMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
        System.exit(0);
    }
}
